# /kafka-streams/k8s/kStream-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kstream-service
  labels:
    app: kstream-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kstream-service
  template:
    metadata:
      labels:
        app: kstream-service
    spec:
      containers:
        - name: kstream-service
          image: yourdockerhubusername/kstream-service:0.1.0
          ports:
            - containerPort: 8082
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092" # Adjust based on your Kafka setup
            - name: SOME_OTHER_ENV_VAR
              value: "value" # Add other environment variables as needed
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
