# /kafka-streams/k8s/kStream-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kstream-service
  labels:
    app: kstream-service
spec:
  selector:
    app: kstream-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
