# /kafka-streams/k8s/kStream-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kstream-service
  namespace: kafka
  labels:
    app: kstream-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kstream-service
  template:
    metadata:
      labels:
        app: kstream-service
    spec:
      containers:
        - name: kstream-service
          image: krizalid69/kstream-service:latest
          ports:
            - containerPort: 8082
          env:  
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "broker:9092" # Adjust based on your Kafka setup
            - name: SOME_OTHER_ENV_VAR
              value: "value" # Add other environment variables as needed
            - name: KAFKA_TOPIC_1
              value: "topic1"
            - name: KAFKA_TOPIC_2
              value: "topic2"
