apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: kafka
spec:
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
  selector:
    app: elasticsearch
