apiVersion: apps/v1
kind: Service
metadata:
  name: consumer-service
spec:
  selector:
    app: consumer-service
  ports:
    - protocols: TCP 
      port: 8080 
      targetPort: 8080
  type: ClusterIP
