apiVersion: v1
kind: Service
metadata:
  name: consumer-service
  namespace: kafka
spec:
  type: NodePort
  selector:
    app: consumer-service
  ports:
    - protocol: TCP  # corrected from "protocols"
      port: 8080 
      targetPort: 8080
  type: ClusterIP
