apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-config
  namespace: kafka
data:
  KAFKA_BOOTSTRAP_SERVERS: "broker:9092"
  KAFKA_GROUP_ID: "csv-consumer-group"
  KAFKA_TOPIC: "trans-topic"
  ELASTICSEARCH_HOST: "elasticsearch"
  ELASTICSEARCH_PORT: "9200"
  ELASTICSEARCH_SCHEME: "http"
  ELASTICSEARCH_INDEX: "kafka-stream-index"
  ES_JAVA_OPTS: "-Xms512m -Xmx512m"
