# deployments/consumer-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  namespace: kafka
  labels:
    app: consumer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-service
  template:
    metadata:
      labels:
        app: consumer-service
    spec:
      containers:
      - name: consumer-service
        image: consumer-service:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: consumer-config
        - secretRef:
            name: elasticsearch-secret
