apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-data-pv
  namespace: kafka
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "~/Documents/amine759/Real-time-ETL/kafka-streams/producer/data"
