apiVersion: v1
kind: Service
metadata:
  name: producer-service
  namespace: kafka
spec:
  type: NodePort
  selector:
    app: producer-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
