apiVersion: v1
kind: Service
metadata:
  name: producer-service
  namespace: kafka
spec:
  type: NodePort
  selector:
    app: producer-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081
