# producer-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
  namespace: kafka
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: producer-service
  template:
    metadata:
      labels:
        app: producer-service
    spec:
      containers:
        - name: producer-service
          image: krizalid69/producer-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "broker:9092" 
            - name: KAFKA_TOPIC_1
              value: "topic1"
            - name: KAFKA_TOPIC_2
              value: "topic2"
          volumeMounts:
            - mountPath: "/app/archive"  # Path where container will access data
              name: docker-data
      volumes:
        - name: docker-data
          persistentVolumeClaim:
            claimName: docker-data-pvc
