name: Scala CI/CD

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches: 
      - "main"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [producer, kStream, consumer]  # Microservices list

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'

    # Run tests for all services (before building Docker images)
    - name: Run tests for all services
      run: sbt test

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Build and push Docker image for each microservice
    - name: Build and push ${{ matrix.service }} image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}-service:latest ./kafka-streams/${{ matrix.service }}
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}-service:latest
